# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hospital Finder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hospital Finder

  pod 'SVProgressHUD'
  pod 'NotificationBannerSwift', '~> 3.0.0'


end
