# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hospital Finder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hospital Finder

  pod 'SVProgressHUD'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'RealmSwift'

  target 'Hospital FinderTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 3.0.0'
    pod 'Nimble', '~> 8.1.1'
    pod 'Cuckoo', '~> 1.4.0'
  end

  target 'Hospital FinderUITests' do
    # Pods for testing
  end

end
